In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import os
from cleaning_utils import *
import numpy as np

# Read in data file

In [4]:
cwd = os.getcwd()
df = pd.read_csv(os.path.join(cwd, "MetObjects.txt"), low_memory=False)

# Example 1 the "Dynasty" column

In [5]:
df["Dynasty"].unique()

array([nan, 'Dynasty 26 or later', 'Late Dynasty 12–13', 'Dynasty 26',
       'Dynasty 18', 'late Dynasty 12 to Dynasty 13', 'Dynasty 13',
       'Dynasty 21', 'Dynasty 19', 'Dynasty 19–20', 'mid-Dynasty 18',
       'Dynasty 12–Dynasty 17', 'Dynasty 12–13', 'late Dynasty 18',
       'Dynasty 4', 'likely Dynasty 19', 'Early Dynasty 18', 'Dynasty 25',
       'Dynasty 22–23', 'Dynasty 5', 'mid–late Dynasty 18',
       'Dynasty 19–22', 'Early Dynasty 12', 'Dynasty 12',
       'Dynasty 11–early 12', 'late Dynasty 12–Dynasty 13',
       'late Dynasty 18–early 19', 'first half of Dynasty 12',
       'late Dynasty 18–early Dynasty 19', 'late Dynasty 12',
       'Dynasty 30', 'Dynasty 11–12', 'Dynasty 20–21',
       'Probably Dynasty 30', 'Dynasty 22–26', 'Dynasty 18–early 19',
       'mid-or late Dynasty 26', 'Dynasty 19 (?)', 'Dynasty 8–11',
       'early Dynasty 18', 'Dynasty 1', 'Dynasty 18, early', 'Dynasty 6',
       'Dynasty 4–5', 'Dynasty 5–6', 'Dynasty 4–mid 5',
       'Dynasty 4, mid–

In [6]:
df[~df["Dynasty"].str.contains("\d\d", regex=True).map(lambda x : False if (type(x)==float) else x)]["Dynasty"].unique()

array([nan, 'Dynasty 4', 'Dynasty 5', 'Dynasty 1', 'Dynasty 6',
       'Dynasty 4–5', 'Dynasty 5–6', 'Dynasty 4–mid 5',
       'Dynasty 4, mid–5th Dynasty', 'Dynasty 3', 'Dynasty 6, first half',
       'Dynasty 6–8', 'Dynasty 6-8', 'Dynasty 4-6', 'early Dynasty 3',
       'Dynasty 9 or later', 'Second Intermediate Period', 'Dynasty 9',
       'Dynasty 8', 'Dynasty 2–3', 'Dynasty 3–4', 'Dynasty 2',
       'Dynasty 2, second half', 'Ptolemaic Dynasty', 'Dynasty 6 (?)',
       'Dynasty 0–1', 'Probably Dynasty 1', 'Dynasty 0–2',
       'Dynasty 2 probably', 'Dynasty 5–8', 'Dynasty 6-9',
       'early dynasty 4–5', 'Dynasty 1–2', 'Dynasty 5 (?)', '6',
       'Dynasty 6 or later', 'Dynasty 3–9', 'Dynasty 5, second half',
       'Ptolemaic', 'Dynasty 1, 3–4', '1', 'Dynasty 3–5', 'Dynasty 2–5',
       'Dynasty 7–8', 'Naqada III–Dynasty 1', 'Naqada II–Dynasty 1',
       'Dynasty 5 or 6', 'Dynasty 0-2', 'Probably late Dynasty 5',
       'Dynasty 8–9', 'Dynasty 0', '9 or later', 'Dynasty 5, end',

In [7]:
df["Dynasty_clean"] = df["Dynasty"].str.extract("(\d\d)")
df[~df["Dynasty_clean"].str.contains("\d\d", regex=True).map(lambda x : False if (type(x)==float) else x)]["Dynasty_clean"].unique()

array([nan], dtype=object)

# Example 2 the 'End Date' column

In [8]:
df["Artist End Date"].unique()

array(['1869      ', '1844      ', nan, ..., '1808      |1809      ',
       '1952      |1952      ',
       '1942      |1954      |          |          '], dtype=object)

In [9]:
df[~df["Artist End Date"].str.contains("(-?\d\d\d\d\|?){1,10}", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date"].unique()

C:\Users\mschm\AppData\Local\Temp\ipykernel_15812\1923886761.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[~df["Artist End Date"].str.contains("(-?\d\d\d\d\|?){1,10}", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date"].unique()


array([nan, '          ', '          |          ',
       '          |          |          ',
       '          |          |          |          ',
       '          |          |          |          |          ',
       '          |          |          |          |          |          |          ',
       '          |          |          |          |          |          ',
       '0         ', '          |0         ', '0         |          ',
       '0         |0         ',
       '          |          |          |          |          |          |          |          '],
      dtype=object)

In [10]:
df["Artist End Date_clean"] = df["Artist End Date"].str.extract("(-?\d\d\d\d\|?){1,10}")
df[~df["Artist End Date_clean"].str.contains("(-?\d\d\d\d\|?){1,10}", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date_clean"].unique()

C:\Users\mschm\AppData\Local\Temp\ipykernel_15812\781919347.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df[~df["Artist End Date_clean"].str.contains("(-?\d\d\d\d\|?){1,10}", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date_clean"].unique()


array([nan], dtype=object)