In [30]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import os
from cleaning_utils import *
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
cwd = os.getcwd()
df = pd.read_csv(os.path.join(cwd, "MetObjects.txt"))

mike_col_list = [i for i in range(0, df.shape[1], 3)]
mike_df = df.iloc[:, mike_col_list]

artist_col_list = list(range(16, 28)) # making list of column index from Q->AB
artist_col_list.insert(0, 0) # Adding the first column as index
artist_df = df.iloc[: , artist_col_list] #subsets originas dataframe 'df'
artist_df = split_rows(artist_df)

mike_artist_cols = [i for i in range(3, artist_df.shape[1], 3)]
mike_artist_df = artist_df.iloc[:, mike_artist_cols]


C:\Users\mschm\AppData\Local\Temp\ipykernel_2548\2169386161.py:2: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(cwd, "MetObjects.txt"))


In [37]:
mike_artist_df["Artist End Date_clean"] = mike_artist_df["Artist End Date"].str.extract("(-?\d\d\d\d)")
mike_artist_df[~mike_artist_df["Artist End Date_clean"].str.contains("-?\d\d\d\d", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date_clean"].unique()

array([nan], dtype=object)

In [43]:
mike_df["Dynasty_clean"] = mike_df["Dynasty"].str.extract("(\d\d)")
mike_df[~mike_df["Dynasty_clean"].str.contains("\d\d", regex=True).map(lambda x : False if (type(x)==float) else x)]["Dynasty_clean"].unique()

C:\Users\mschm\AppData\Local\Temp\ipykernel_2548\1901317313.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mike_df["Dynasty_clean"] = mike_df["Dynasty"].str.extract("(\d\d)")


array([nan], dtype=object)

In [50]:
mike_df["Artist End Date_clean"] = mike_df["Artist End Date"].str.extract("(\d\d\d\d)")
mike_df[~mike_df["Artist End Date_clean"].str.contains("\d\d\d\d", regex=True).map(lambda x : False if (type(x)==float) else x)]["Artist End Date_clean"].unique()

C:\Users\mschm\AppData\Local\Temp\ipykernel_2548\1130483862.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mike_df["Artist End Date_clean"] = mike_df["Artist End Date"].str.extract("(\d\d\d\d)")


array([nan], dtype=object)

In [ ]:
#made it up to credit line. Start with credit line and move right through columns

In [40]:
mike_df.head(2)

Object Number  Is Public Domain         Department  \
0    1979.486.1             False  The American Wing   
1    1980.264.5             False  The American Wing   

                          Title Dynasty Constituent ID    Artist Display Name  \
0  One-dollar Liberty Head Coin     NaN          16429  James Barton Longacre   
1  Ten-dollar Liberty Head Coin     NaN            107     Christian Gobrecht   

        Artist Alpha Sort Artist End Date  \
0  Longacre, James Barton      1869         
1     Gobrecht, Christian      1844         

                      Artist Wikidata URL  Object End Date  \
0  https://www.wikidata.org/wiki/Q3806459             1853   
1  https://www.wikidata.org/wiki/Q5109648             1901   

                          Credit Line State Region Locus Classification  \
0  Gift of Heinz L. Stoppelmann, 1979   NaN    NaN   NaN            NaN   
1  Gift of Heinz L. Stoppelmann, 1980   NaN    NaN   NaN            NaN   

  Object Wikidata URL Tags  
0                 NaN  NaN  
1                 NaN  NaN